apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-api
  namespace: expense-dashboard
  labels:
    app: expense-api
spec:
  replicas: 2
  revisionHistoryLimit: 5
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: expense-api
  template:
    metadata:
      labels:
        app: expense-api
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: expense-api
          image: 180294218913.dkr.ecr.us-east-1.amazonaws.com/capstone-api:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: expense-api-secrets
                  key: MONGO_URI
            - name: MONGO_DB
              valueFrom:
                secretKeyRef:
                  name: expense-api-secrets
                  key: MONGO_DB
                  optional: true
            - name: MONGO_COLLECTION
              valueFrom:
                secretKeyRef:
                  name: expense-api-secrets
                  key: MONGO_COLLECTION
                  optional: true
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: expense-api-secrets
                  key: JWT_SECRET
          ports:
            - containerPort: 3000
              name: http
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
