apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expense-mongo-data
  namespace: expense-dashboard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-mongo
  namespace: expense-dashboard
  labels:
    app: expense-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-mongo
  template:
    metadata:
      labels:
        app: expense-mongo
    spec:
      containers:
        - name: expense-mongo
          image: mongo:7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
              name: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: expense-api-secrets
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: expense-api-secrets
                  key: MONGO_ROOT_PASSWORD
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: expense-api-secrets
                  key: MONGO_DB
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          startupProbe:
            tcpSocket:
              port: 27017
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 20
            periodSeconds: 20
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: expense-mongo-data
---
apiVersion: v1
kind: Service
metadata:
  name: expense-mongo
  namespace: expense-dashboard
  labels:
    app: expense-mongo
spec:
  type: ClusterIP
  selector:
    app: expense-mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
