apiVersion: v1
kind: Service
metadata:
  name: expense-frontend
  namespace: expense-dashboard
  labels:
    app: expense-frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: expense-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80