apiVersion: v1
kind: Service
metadata:
  name: expense-api
  namespace: expense-dashboard
  labels:
    app: expense-api
spec:
  type: ClusterIP
  selector:
    app: expense-api
  ports:
    - name: http
      port: 4000
      targetPort: 3000
