apiVersion: v1
kind: Secret
metadata:
  name: expense-api-secrets
  namespace: expense-dashboard
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: expense_user
  MONGO_ROOT_PASSWORD: expense_pass
  MONGO_URI: mongodb://expense_user:expense_pass@expense-mongo:27017/expense_dashboard?authSource=admin
  MONGO_DB: expense_dashboard
  MONGO_COLLECTION: transactions
  JWT_SECRET: replace-with-a-long-random-secret
